# Generated by Django 5.1.7 on 2025-04-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GST_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('date_of_filing', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
